### ISSUE TITLE
Include the plugin in the CloudFoundry Repo?

### ISSUE THREAD

**Issue by goehmen** [cloudfoundry-community/cf-plugin-seed#4]
Hey Long:

It would be awesome if you submitted a PR to the CF CLI team so we could include your plugins on the cf community plugin site.  http://plugins.cloudfoundry.org   

Instructions are here:  https://github.com/cloudfoundry-incubator/cli-plugin-repo#submitting-plugins

Best

Greg Oehmen
CF Product Manager -  CLI

**Comment by jhunt** [comment]
This plugin is deprecated now.
